// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.MVC2.Models
{
    public partial class VehicleMake
    {
        public VehicleMake()
        {
            VehicleModel = new HashSet<VehicleModel>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Abrv { get; set; }

        public virtual ICollection<VehicleModel> VehicleModel { get; set; }
    }
}